services:
  - name: Test Service
    port: 8888
    endpoints:
      - path: /
        response: "Hello from Mockintosh!"
      - path: /health
        response:
          body: "OK"
          status: 200
